baseURL = 'https://devblog.dziubiak.pl/'
languageCode = 'en-us'
title = "Marian's Blog"
theme = 'hugo-book'

# theme
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']
[params]
    BookTheme = 'dark'
    BookSection = '*' # all sections make a menu
    BookComments = false
    BookPortableLinks = true # experimental to use normal links instead of {{< relref >}}
    BookLogo = 'manio.png'

    images = ['blog.jpg']

[markup.goldmark.renderer]
    unsafe = true # allow HTML in posts
